//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_MobPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_niveau_experience
    {
        public int id { get; set; }
        public string nom_niveau_experience { get; set; }
        public int domaine_id { get; set; }
        public Nullable<int> profil_id { get; set; }
        public Nullable<int> offre_emploi_id { get; set; }
    
        public virtual T_domaine T_domaine { get; set; }
        public virtual T_profil T_profil { get; set; }
        public virtual T_offre_emploi T_offre_emploi { get; set; }
    }
}
