//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_MobPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_num_tel
    {
        public int id { get; set; }
        public string telephone { get; set; }
        public Nullable<int> entreprise_id { get; set; }
    
        public virtual T_entreprise T_entreprise { get; set; }
    }
}
