//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_MobPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_num_tel
    {
        public int id { get; set; }
        public string telephone { get; set; }
        public Nullable<int> entreprise_id { get; set; }
    
        public virtual T_entreprise T_entreprise { get; set; }
    }
}
