//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_MobPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_offre_emploi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_offre_emploi()
        {
            this.T_niveau_experience = new HashSet<T_niveau_experience>();
            this.T_offre_emploi_competences = new HashSet<T_offre_emploi_competences>();
            this.T_offre_emploi_langues = new HashSet<T_offre_emploi_langues>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date_publication { get; set; }
        public Nullable<System.DateTime> date_suppression { get; set; }
        public Nullable<bool> ouvert_externe { get; set; }
        public string url_site { get; set; }
        public Nullable<bool> teletravail_autorise { get; set; }
        public Nullable<bool> full_teletravail { get; set; }
        public Nullable<int> site_id { get; set; }
        public Nullable<int> statut_id { get; set; }
        public Nullable<int> entreprise_id { get; set; }
        public Nullable<int> type_contrat_id { get; set; }
        public Nullable<int> niveau_experience_id { get; set; }
    
        public virtual T_entreprise T_entreprise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_niveau_experience> T_niveau_experience { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_offre_emploi_competences> T_offre_emploi_competences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_offre_emploi_langues> T_offre_emploi_langues { get; set; }
        public virtual T_site T_site { get; set; }
        public virtual T_statut T_statut { get; set; }
        public virtual T_type_contrat T_type_contrat { get; set; }
    }
}
