//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace Projet_MobPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_offre_emploi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_offre_emploi()
        {
            this.T_competences = new HashSet<T_competences>();
            this.T_langues = new HashSet<T_langues>();
        }
    
        public int id { get; set; }
        [Display(Name = "Nom")]
        public string nom { get; set; }
        [Display(Name = "Description")]
        public string description { get; set; }
        [Display(Name = "Date de publication")]
        public Nullable<System.DateTime> date_publication { get; set; }
        [Display(Name = "Date de suppression")]
        public Nullable<System.DateTime> date_suppression { get; set; }
        [Display(Name = "Ouvert ou externe")]
        public Nullable<bool> ouvert_externe { get; set; }
        [Display(Name = "Lien du site web")]
        public string url_site { get; set; }
        [Display(Name = "Télétravail autorisé")]
        public Nullable<bool> teletravail_autorise { get; set; }
        [Display(Name = "Télétravail partiel ou complet")]
        public Nullable<bool> full_teletravail { get; set; }
        [Display(Name = "Site")]
        public Nullable<int> site_id { get; set; }
        [Display(Name = "Statut")]
        public Nullable<int> statut_id { get; set; }
        [Display(Name = "Entreprise")]
        public Nullable<int> entreprise_id { get; set; }
        [Display(Name = "Type de contrat recherché")]
        public Nullable<int> type_contrat_id { get; set; }
        [Display(Name = "Niveau d'expérience requis")]
        public Nullable<int> niveau_experience_id { get; set; }
    
        public virtual T_entreprise T_entreprise { get; set; }
        public virtual T_site T_site { get; set; }
        public virtual T_statut T_statut { get; set; }
        public virtual T_type_contrat T_type_contrat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_competences> T_competences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_langues> T_langues { get; set; }
    }
}
