//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_MobPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_profil_langues
    {
        public int id { get; set; }
        public int profil_id { get; set; }
        public int langues_id { get; set; }
        public Nullable<int> level_langues { get; set; }
        public string commentaire { get; set; }
    
        public virtual T_langues T_langues { get; set; }
        public virtual T_profil T_profil { get; set; }
    }
}
