INSERT INTO [dbo].[T_langues] ([id], [nom_langue]) VALUES (1, N'Français')
INSERT INTO [dbo].[T_langues] ([id], [nom_langue]) VALUES (2, N'Anglais')
INSERT INTO [dbo].[T_langues] ([id], [nom_langue]) VALUES (3, N'Espagnol')
INSERT INTO [dbo].[T_langues] ([id], [nom_langue]) VALUES (4, N'Allemand')
INSERT INTO [dbo].[T_langues] ([id], [nom_langue]) VALUES (5, N'Chinois')
INSERT INTO [dbo].[T_langues] ([id], [nom_langue]) VALUES (6, N'Japonais')
INSERT INTO [dbo].[T_langues] ([id], [nom_langue]) VALUES (7, N'Portugais')
INSERT INTO [dbo].[T_langues] ([id], [nom_langue]) VALUES (8, N'Russe')